# Generated by Django 3.1.7 on 2021-03-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_key', models.IntegerField()),
                ('manually_requested', models.BooleanField()),
                ('votes', models.IntegerField()),
                ('internal_url', models.CharField(max_length=2000)),
                ('external_url', models.CharField(blank=True, max_length=2000)),
                ('artist', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('duration', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Songs')),
                ('favorite', models.BooleanField(verbose_name='Favorites')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spotify_url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text='Are you male or female ? .', max_length=6, verbose_name='Gender')),
                ('date_of_birth', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
                ('artists', models.CharField(db_index=True, max_length=200, null=True)),
                ('spotify_id', models.CharField(max_length=200, null=True, unique=True)),
                ('apple_music_id', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
    ]
